# Generated by Django 5.0.7 on 2024-07-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('ratings', models.IntegerField(default=0)),
                ('favoured', models.BooleanField(default=False)),
                ('add_to_cart', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0.0)),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('Red', 'red'), ('Green', 'green'), ('Blue', 'blue'), ('Yellow', 'yellow'), ('Purple', 'purple'), ('Orange', 'orange'), ('Pink', 'pink'), ('Teal', 'teal'), ('Gray', 'gray'), ('Brown', 'brown')], help_text='Select a color for the product.', unique=True)),
            ],
            options={
                'verbose_name_plural': 'All Products',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='app.product')),
            ],
            options={
                'verbose_name_plural': 'All Images',
            },
        ),
        migrations.CreateModel(
            name='AttributeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attributekey')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
