# Generated by Django 5.0.7 on 2024-07-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('Red', 'red'), ('Green', 'green'), ('Blue', 'blue'), ('Yellow', 'yellow'), ('Purple', 'purple'), ('Orange', 'orange'), ('Pink', 'pink'), ('Teal', 'teal'), ('Gray', 'gray'), ('Brown', 'brown')], help_text='Select a color for the product', unique=True),
        ),
    ]
