# Generated by Django 5.0.6 on 2024-07-13 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_options_alter_customer_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 19, 48, 27, 24784)),
        ),
    ]
